### PR TITLE
Add Vipul to the list

### PR DESCRIPTION
**Pull request by vipulroxx**

### CODE REVIEW

**Comment by samdroid-apps** [comment]
Thanks for the patch.

(Normally, I begin fighting with you about something and make you submit more patches...)

But this is a good patch, so I will merge it.

What is your gci username?

**Comment by tradzik** [comment]
@vipulroxx Please make new PR including your GCI NAME in the file, as in task.

CC: @samdroid-apps

**Comment by samdroid-apps** [comment]
Sorry, I did not read the task description

**Comment by vipulroxx** [comment]
my user name is mYsteRi0us

**Comment by vipulroxx** [comment]
*instead of editing i wrote it in the comments so that it can follow GCI rule also...I haven't seen that you merged mine :)

**Comment by samdroid-apps** [comment]
Sorry, which gci rule?

I have merged this patch.

**Comment by vipulroxx** [comment]
I am familiar to git as I have done alot of contributions. I LOVE Git. Love it!!!!

**Pull request merged**
