### PR TITLE
Added niels.md file to the repository

### PR DESCRIPTION
**Pull request by 1Niels**
## Feelings:

I am some what familiar with using git but usually for private use and usually I do not push to Github and instead stay in the desktop app. I really hope that in the future I can commit more to repositories belonging to other people instead of just my own. Thanks!

### CODE REVIEW

**Comment by samdroid-apps** [comment]
Great!  Please link to this from your task and mark it as completed.

**Comment by 1Niels** [comment]
Thanks! I will but I'm doing another task right now and I am only allowed
to do officially submit one task at a time.

On Tue, Dec 8, 2015 at 3:49 PM, Sam notifications@github.com wrote:

> Great! Please link to this from your task and mark it as completed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tradzik/sugar-labs-gci-test/pull/8#issuecomment-163013925
> .

## 

Niels

**Comment by samdroid-apps** [comment]
It's fine, I don't think that missing this task will count against you in the end (at all)

**Comment by 1Niels** [comment]
Thanks for the reassurance! Also are you Sam, the Google Code-in grand
prize winner from last year?

On Tue, Dec 8, 2015 at 4:05 PM, Sam notifications@github.com wrote:

> It's fine, I don't think that missing this task will count against you in
> the end (at all)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tradzik/sugar-labs-gci-test/pull/8#issuecomment-163017448
> .

## 

Niels

**Comment by tradzik** [comment]
@1Niels Yeah, he is :smile_cat: You can claim this task later, when you finish your current one. There are 50 instances of it!

**Pull request merged**
